# -*- coding: utf-8 -*-
"""
/***************************************************************************
 BNGAI Labelling
                                 A QGIS plugin
 asads
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2024-06-25
        git sha              : $Format:%H$
        copyright            : (C) 2024 by AiDash
        email                : subhadip.de@aidash.com
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""
from qgis.PyQt.QtCore import QSettings, QTranslator, QCoreApplication
from qgis.PyQt.QtGui import QIcon
from qgis.PyQt.QtWidgets import QAction
from .BNGAILabellingService import *
# Initialize Qt resources from file resources.py
from .resources import *
# Import the code for the dialog
import os.path
import inspect

cmd_folder = os.path.split(inspect.getfile(inspect.currentframe()))[0]


class BNGAILabelling:
    """QGIS Plugin Implementation."""

    def __init__(self, iface):
        """Constructor.

        :param iface: An interface instance that will be passed to this class
            which provides the hook by which you can manipulate the QGIS
            application at run time.
        :type iface: QgsInterface
        """
        # Save reference to the QGIS interface
        self.iface = iface

    def initGui(self):
        """Create the menu entries and toolbar icons inside the QGIS GUI."""

        icon = os.path.join(os.path.join(cmd_folder, 'icon_v2.png'))
        self.action = QAction(QIcon(icon), 'BNGAILabelling', self.iface.mainWindow())
        self.action.triggered.connect(self.run)
        self.iface.addPluginToMenu('&My Plugins', self.action)
        self.iface.addToolBarIcon(self.action)

    def unload(self):
        """Removes the plugin menu item and icon from QGIS GUI."""
        self.iface.removeToolBarIcon(self.action)
        self.iface.removePluginMenu('&My Plugins', self.action)
        del self.action

    def run(self):
        """Run method that performs all the real work"""

        run_bngai_labelling()
