# -*- coding: utf-8 -*-
"""
/***************************************************************************
 BNG AI QGIS Plugin
                                 A QGIS plugin
 Loads BNGAI Baseline Map
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2025-04-23
        copyright            : (C) 2025 by aidash
        email                : vivek.tiwari@aidash.com
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load BngAiPlugin class from file bngai
    
    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    from .plugin import BngAiPlugin
    return BngAiPlugin(iface)
