# -*- coding: utf-8 -*-
"""
/***************************************************************************
 bngaiPOC
                                 A QGIS plugin
 Loads BNGAI Baseline Map
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2025-04-23
        git sha              : $Format:%H$
        copyright            : (C) 2025 by aidash
        email                : vivek.tiwari@aidash.com
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""
from qgis.PyQt.QtCore import QSettings, QTranslator, QCoreApplication
from qgis.PyQt.QtGui import QIcon
from qgis.PyQt.QtWidgets import QAction, QMessageBox
from qgis.core import QgsMessageLog, QgsTask, QgsApplication, QgsVectorLayer, QgsFeature, QgsGeometry, QgsPointXY, QgsProject, QgsWkbTypes, QgsCoordinateReferenceSystem

# Initialize Qt resources from file resources.py
from .resources import *
# Import the code for the dialog
from .bngai_dialog import bngaiPOCDialog
from .utils.apiclient import GraphQLClient, GraphQLTask
import os.path


class bngaiPOC:
    """QGIS Plugin Implementation."""

    def __init__(self, iface):
        """Constructor.

        :param iface: An interface instance that will be passed to this class
            which provides the hook by which you can manipulate the QGIS
            application at run time.
        :type iface: QgsInterface
        """
        # Save reference to the QGIS interface
        self.iface = iface
        # initialize plugin directory
        self.plugin_dir = os.path.dirname(__file__)
        # initialize locale
        locale = QSettings().value('locale/userLocale')[0:2]
        locale_path = os.path.join(
            self.plugin_dir,
            'i18n',
            'bngaiPOC_{}.qm'.format(locale))

        if os.path.exists(locale_path):
            self.translator = QTranslator()
            self.translator.load(locale_path)
            QCoreApplication.installTranslator(self.translator)

        # Declare instance attributes
        self.actions = []
        self.menu = self.tr(u'&bngaiBaselineLoader')

        # Check if plugin was started the first time in current QGIS session
        # Must be set in initGui() to survive plugin reloads
        self.first_start = None

    # noinspection PyMethodMayBeStatic
    def tr(self, message):
        """Get the translation for a string using Qt translation API.

        We implement this ourselves since we do not inherit QObject.

        :param message: String for translation.
        :type message: str, QString

        :returns: Translated version of message.
        :rtype: QString
        """
        # noinspection PyTypeChecker,PyArgumentList,PyCallByClass
        return QCoreApplication.translate('bngaiPOC', message)


    def add_action(
        self,
        icon_path,
        text,
        callback,
        enabled_flag=True,
        add_to_menu=True,
        add_to_toolbar=True,
        status_tip=None,
        whats_this=None,
        parent=None):
        """Add a toolbar icon to the toolbar.

        :param icon_path: Path to the icon for this action. Can be a resource
            path (e.g. ':/plugins/foo/bar.png') or a normal file system path.
        :type icon_path: str

        :param text: Text that should be shown in menu items for this action.
        :type text: str

        :param callback: Function to be called when the action is triggered.
        :type callback: function

        :param enabled_flag: A flag indicating if the action should be enabled
            by default. Defaults to True.
        :type enabled_flag: bool

        :param add_to_menu: Flag indicating whether the action should also
            be added to the menu. Defaults to True.
        :type add_to_menu: bool

        :param add_to_toolbar: Flag indicating whether the action should also
            be added to the toolbar. Defaults to True.
        :type add_to_toolbar: bool

        :param status_tip: Optional text to show in a popup when mouse pointer
            hovers over the action.
        :type status_tip: str

        :param parent: Parent widget for the new action. Defaults None.
        :type parent: QWidget

        :param whats_this: Optional text to show in the status bar when the
            mouse pointer hovers over the action.

        :returns: The action that was created. Note that the action is also
            added to self.actions list.
        :rtype: QAction
        """

        icon = QIcon(icon_path)
        action = QAction(icon, text, parent)
        action.triggered.connect(callback)
        action.setEnabled(enabled_flag)

        if status_tip is not None:
            action.setStatusTip(status_tip)

        if whats_this is not None:
            action.setWhatsThis(whats_this)

        if add_to_toolbar:
            # Adds plugin icon to Plugins toolbar
            self.iface.addToolBarIcon(action)

        if add_to_menu:
            self.iface.addPluginToMenu(
                self.menu,
                action)

        self.actions.append(action)

        return action

    def initGui(self):
        """Create the menu entries and toolbar icons inside the QGIS GUI."""

        icon_path = ':/plugins/bngai/icon.png'
        self.add_action(
            icon_path,
            text=self.tr(u'Load Baseline'),
            callback=self.run,
            parent=self.iface.mainWindow())

        # will be set False in run()
        self.first_start = True


    def unload(self):
        """Removes the plugin menu item and icon from QGIS GUI."""
        for action in self.actions:
            self.iface.removePluginMenu(
                self.tr(u'&bngaiBaselineLoader'),
                action)
            self.iface.removeToolBarIcon(action)

    def fetch_graphql_data(self, authorization=None, organization_id=None, site_revision_id=None, application_component=None):
        """Fetch data from GraphQL server asynchronously
        
        :param authorization: Authorization token, defaults to None (will use default token)
        :type authorization: str, optional
        :param organization_id: Organization ID, defaults to None (will use default ID)
        :type organization_id: str, optional
        :param site_revision_id: Site revision ID, defaults to None (will use default ID)
        :type site_revision_id: str, optional
        :param application_component: Application component name, defaults to None (will use default value)
        :type application_component: str, optional
        """
        QgsMessageLog.logMessage("Initializing GraphQL data fetch...", "BNGAI Plugin", level=0)
        
        # GraphQL endpoint URL
        url = "https://isms-backend-uat-universel.aidash.io/graphql"
        
        # Create and start the task
        task = GraphQLTask(
            "Fetching GraphQL data", 
            url, 
            GraphQLClient.getHabitatGeometry(), 
            GraphQLClient.get_default_variables(site_revision_id, application_component), 
            GraphQLClient.get_default_headers(authorization, organization_id), 
            self
        )
        QgsApplication.taskManager().addTask(task)
        
        QgsMessageLog.logMessage("Task added to task manager", "BNGAI Plugin", level=0)
        return None

    def fetch_bng_plan_data(self, bng_plan_id, authorization=None, organization_id=None):
        """Fetch BNG plan data from GraphQL server
        
        :param bng_plan_id: BNG plan ID to fetch
        :type bng_plan_id: str
        :param authorization: Authorization token, defaults to None (will use default token)
        :type authorization: str, optional
        :param organization_id: Organization ID, defaults to None (will use default ID)
        :type organization_id: str, optional
        """
        QgsMessageLog.logMessage(f"Initializing BNG Plan data fetch for plan ID: {bng_plan_id}", "BNGAI Plugin", level=0)
        
        # GraphQL endpoint URL
        url = "https://isms-backend-uat-universel.aidash.io/graphql"
        
        # Create and start the task
        from .utils.apiclient import BngPlanGraphQLTask
        task = BngPlanGraphQLTask(
            "Fetching BNG Plan data", 
            url, 
            GraphQLClient.getBngPlanDetail(), 
            GraphQLClient.get_bng_plan_variables(bng_plan_id), 
            GraphQLClient.get_default_headers(authorization, organization_id), 
            self
        )
        QgsApplication.taskManager().addTask(task)
        
        QgsMessageLog.logMessage("BNG Plan task added to task manager", "BNGAI Plugin", level=0)
            return None

    def run(self):
        """Run method that performs all the real work"""

        # Create the dialog with elements (after translation) and keep reference
        # Only create GUI ONCE in callback, so that it will only load when the plugin is started
        if self.first_start == True:
            self.first_start = False
            self.dlg = bngaiPOCDialog()

        # show the dialog
        self.dlg.show()
        # Run the dialog event loop
        result = self.dlg.exec_()
        # See if OK was pressed
        if result:
            # Fetch BNG plan data instead of habitat geometry
            # Example BNG plan ID - replace with actual ID or get from UI
            # This should be a valid UUID from your system
            # Using the BNG plan ID from the working curl example
            # If this ID doesn't have habitats, try these alternatives:
            bng_plan_id = "cda9347c-9b26-4b97-87c2-51c08fdebefe"
            # Uncomment one of these if the above ID doesn't have habitats
            # bng_plan_id = "9113d037-9577-40b7-bd66-e9738536d99e"  # Original ID that worked for habitat geometry
            # bng_plan_id = "12a15c7a-7f33-49fd-9cb5-7c964f5e6a09"  # Another ID to try
            
            QgsMessageLog.logMessage(f"Fetching BNG plan with ID: {bng_plan_id}", "BNGAI Plugin", level=0)
            
            self.fetch_bng_plan_data(
                bng_plan_id,
                authorization="eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6InNyZTZ1c05Oa0lmYzJiaXphaHU4USJ9.eyJodHRwczovL2lzbXMuYWlkYXNoLmlvL2NsYWltcyI6eyJlbWFpbCI6ImJhYmx1QGFpZGFzaC5jb20iLCJpc0ZlZGVyYXRlZExvZ2luIjpmYWxzZSwidXNlcl9lbWFpbF92ZXJpZmllZCI6dHJ1ZX0sImh0dHBzOi8vaXNtcy11YXQtdW5pdmVyc2FsLmFpZGFzaC5pby9jbGFpbXMiOnsiZW1haWwiOiJiYWJsdUBhaWRhc2guY29tIiwiaXNGZWRlcmF0ZWRMb2dpbiI6ZmFsc2UsInVzZXJfZW1haWxfdmVyaWZpZWQiOnRydWV9LCJpc3MiOiJodHRwczovL2Rldi1pbThrc2Nxdy5ldS5hdXRoMC5jb20vIiwic3ViIjoiYXV0aDB8NjY2MmMwODkyMDAyMzQ3OTk4OGE5NGQ5IiwiYXVkIjpbImh0dHBzOi8vZGV2LWltOGtzY3F3LmV1LmF1dGgwLmNvbS9hcGkvdjIvIiwiaHR0cHM6Ly9kZXYtaW04a3NjcXcuZXUuYXV0aDAuY29tL3VzZXJpbmZvIl0sImlhdCI6MTc0NjE2NTQxMiwiZXhwIjoxNzQ2MjUxNzk1LCJzY29wZSI6Im9wZW5pZCBwcm9maWxlIGVtYWlsIiwiYXpwIjoid3cyWHVDOG56YlM0d0xOR0xjWXpIVWxjQXlNbFpiMm4ifQ.mqxPBjo-41JDsEg4LOhwt7O6Y2zP_OgQKw4gq8o_qq3LCWP3bFppJyDIX4aTAmk43J4IWnfCmcQf7Q1Iwb-d9eIfc6cXtUn9ep45TjF5AyVDGRLs0gxjpKqwFz3jzcaVwZP9vhtgLBEdJzlQiKmSR7DycRfYtmk-Opl_BKLpx1ch-USnGyxNVY7LfjAkV3DaJd44vmPitt9CzMZhSYKyPHC2JUtlAy9dbH6jqXPwCPLwjfEEZiGGUoqlerBPK4bCFVQE0ZnDvPx6541pzGASB3zWCjVXnmwKL-FXloJtKccB5lHahaRqT7uX1nb6vRrCwes2VnO-FpYiu1VeEr81IA",
                organization_id="3255e96f-7b65-4f41-80e4-7ede31e7ec3a"
            )
            
            QgsMessageLog.logMessage("BNG plan data fetch requested", "BNGAI Plugin", level=0)
